export enum ServerErrors {
    INSUFFICENT_INFO = 'INSUFFICENT_INFO',
    NOT_AUTHORIZED = 'NOT_AUTHORIZED',
    ANALYTICS_INSUFFICENT_INFO = "ANALYTICS_INSUFFICENT_INFO",
    INVALID_REPSONSE = "INVALID_REPSONSE"
}